user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	sendfile on;
	keepalive_timeout 65;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;

	ssl_certificate     /etc/ssl/inception/inception.crt;
	ssl_certificate_key /etc/ssl/inception/inception.key;

	server {
		listen 443 ssl;
		server_name yourlogin.42.fr;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include fastcgi_params;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_pass wordpress:9000;
		}

		location ~* /(?:\.ht|wp-config\.php|readme\.html) {
			deny all;
		}
	}
}

