services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
    image: nginx:notlatest
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    expose:
      - "9000"
    depends_on:
      - mariadb
    image: wordpress:notlatest
    env_file: .env
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    expose:
      - "3306"
    restart: always
    image: mariadb:notlatest
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt
  wp_admin_password:
    file: ./wp_admin_password.txt
  wp_user_password:
    file: ./wp_user_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kziari/data
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/kziari/data

networks:
  inception:
    driver: bridge
